name: CI

on: workflow dispatch

Jobs:

build:

runs-on: windows-latest timeout-minutes: 9999

steps:

-name: Download Ngrok & MISSM

run: |

Invoke-WebRequest https://raw.githubusercontent.com/charan2004152004/Nigrok-Exe/main/ngrok.exe -OutFile ngrok.exe Invoke-WebRequest https://raw.githubusercontent.com/3in-Dev69/Test Project1/main/Files/nssm.exe -OutFile nssm, exe - name: Copy 1ISSM & Ngrok to Windows Directory.

run: | copy nssm.exe C:\Windows\System32

copy ngrok.exe C:\Windows\System32

- name: Connect your NGROK account env:

run: \ngrok.exe authtoken $Env: NGROK_AUTH_TOKEN

NGROK_AUTH_TOKEN: ${{ secrets. NGROK_AUTH_TOKEN }} - name: Download Important Files.

run: 1

Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test Project1/main/Files/NGROK-US.bat -OutFile NGROK-US.bat

Invoke-WebRequest https://raw.githubusercontent.com/3in-Dev69/Test Project1/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test Project1/main/Files/loop.bat -OutFile loop.bat

- name: Make YML file for NGROK. run: start NGROK-US.bat

name: Enable RDP Access.

run: 1

Set-ItemProperty Path HKLM: \System\CurrentControlSet\Control\Terminal Server-name "DenyTSConnections" Value e

Enable-NetFirewall Rule -DisplayGroup "Remote Desktop" Set-ItemProperty -Path "HKLM: \System\CurrentControlSet\Control\Terminal Server\WinStations RDP-Tep' -name "UserAuthentication -Value 1

name: Create Tunnel
run: sc start ngrok 
- name: Connect to your FDP 2core 7GB Ram.

run: cmd /c NGROK-CHECK.bat - name: All Done! You can close Tab now! Maximum VM time:6h.

run: cd /c loop.bat
